twig:
    paths:
        '%kernel.project_dir%/%notacms.local_dir%/templates': ''
        '%kernel.project_dir%/templates': 'base'
    file_name_pattern: '*.twig'
    globals:
        cf_analytics_token: '%env(CF_ANALYTICS_TOKEN)%'
        notacms_project_url: 'https://github.com/holas1337/notACMS'

when@test:
    twig:
        strict_variables: true
